### ISSUE TITLE
ignore_paths is not ignoring top level paths

### ISSUE THREAD

**Issue by justin808** [YorickPeterse/ruby-lint#144] opened 2015-04-06 07:05 UTC
Rails 4.2 app, using ruby-2.1.5. I'm running ruby-lint like:

    ruby-lint .

My config file is: 

```yml
---
presenter: syntastic

directories:
  - app
  - config
  - spec

ignore_paths:
  - client
  - node_modules
```

The problem I'm seeing is that the `ignore_paths` option is ignored.

**Comment by YorickPeterse** [comment] 2015-04-06 10:57
Ignored in what way, do you mean ruby-lint is still trying to load files from `./client` and `./node_modules`? On a side note, if all directories resides in `.` then this combination of both `directories` and `ignore_paths` is redundant. 

By using `directories` you already specify a whitelist of directories to use, meaning `client` and `node_modules` won't be searched. An example of using the two together can be seen here: https://github.com/YorickPeterse/ruby-lint/blob/master/ruby-lint.yml

**Comment by justin808** [comment] 2015-04-06 18:04
Basically, the expected is not the behavior I'm seeing.

I have directories:

client/node_modules
node_modules

That contain libraries which I don't want to lint.

How do I make sure those are always excluded?

Is the problem that I'm specifying `.` and `.` directly contains the directories I want to exclude, so it's overriding those?

**Comment by justin808** [comment] 2015-04-06 19:01
OK so better just to whitelist directories?

and run 

```
ruby-lint .
```

thanks!

**Comment by YorickPeterse** [comment] 2015-04-06 20:08
@justin808 Yes, that should do the trick. Feel free to close the issue if that solves the problem.

**Comment by justin808** [comment] 2015-04-06 21:32
@YorickPeterse thanks for the help. However, this is not working:

```
ruby-lint .                                                                                                                                                            client/node_modules/bootstrap-sass/tasks/converter/less_conversion.rb:W:299:22: ambiguous first argument; put parentheses or a space even after the operator
```

```
---
presenter: syntastic

directories:
  - app
  - config
  - spec
```

**Comment by justin808** [comment] 2015-04-06 21:34
@YorickPeterse You can try it out here: https://github.com/justin808/react-webpack-rails-tutorial/pull/29

**Comment by YorickPeterse** [comment] 2015-04-06 21:56
@justin808 What exactly is not working? For me no output is produced, which could be perfectly valid depending on the code being analysed.

**Comment by justin808** [comment] 2015-04-06 22:06
@YorickPeterse when I run it locally, it seems to ignore the "directories" and ignore list. Any ideas? I'm 100% sure the config file is being used.

**Comment by YorickPeterse** [comment] 2015-04-06 22:30
@justin808 What do you mean with it ignores the option? Could you paste the output of `ruby-lint --version` and the exact output of running `ruby-lint .`?

**Comment by justin808** [comment] 2015-04-07 00:34
```
➜  ~/j/react/react-webpack-rails-tutorial (rubocop-integration u=) ✗ ruby-lint --version                                                                                                                                                                     1 ↵ ✹ [11:28:36]
ruby-lint v2.0.3 on ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
➜  ~/j/react/react-webpack-rails-tutorial (rubocop-integration u=) ✗ ruby-lint .                                                                                                                                                                                 ✹ [14:33:06]
/Users/justin/j/react/react-webpack-rails-tutorial/client/node_modules/bootstrap-sass/tasks/converter/less_conversion.rb:W:299:22: ambiguous first argument; put parentheses or a space even after the operator
➜  ~/j/react/react-webpack-rails-tutorial (rubocop-integration u=) ✗ cat ruby-lint.yml                                                                                                                                                                       1 ↵ ✹ [14:33:51]
---
presenter: syntastic

directories:
  - app
  - config
  - spec

#ignore_paths:
#  - client
#  - node_modules
#  - client/**/*

analysis_classes:
  #  - argument_amount
  - pedantics
  - shadowing_variables
  # Too many false positives for these
  #  - undefined_methods
  #  - undefined_variables
  #  - unused_variables
  - useless_equality_checks
```

**Comment by YorickPeterse** [comment] 2015-04-07 08:39
The particular warning you're seeing is emitted by the parser Gem ruby-lint uses. I can't seem to reproduce this using Ruby 2.2:

```
tmp $ git clone git@github.com:justin808/react-webpack-rails-tutorial.git
Cloning into 'react-webpack-rails-tutorial'...
remote: Counting objects: 965, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 965 (delta 1), reused 0 (delta 0), pack-reused 958
Receiving objects: 100% (965/965), 586.13 KiB | 238.00 KiB/s, done.
Resolving deltas: 100% (514/514), done.
Checking connectivity... done.
tmp $ cd react-webpack-rails-tutorial/
react-webpack-rails-tutorial $ git checkout rubocop-integration 
chruby: unknown Ruby: 2.1.5
Branch rubocop-integration set up to track remote branch rubocop-integration from origin.
Switched to a new branch 'rubocop-integration'
react-webpack-rails-tutorial $ chruby 2.2
react-webpack-rails-tutorial $ gem install ruby-lint
Fetching: ruby-lint-2.0.3.gem (100%)
Please report any issues at: https://github.com/YorickPeterse/ruby-lint/issues/new
Successfully installed ruby-lint-2.0.3
1 gem installed
react-webpack-rails-tutorial $ cat ruby-lint.yml 
---
presenter: syntastic

directories:
  - app
  - config
  - spec

ignore_paths:
  - client
  - node_modules
  - client/**/*

analysis_classes:
#  - argument_amount
  - pedantics
  - shadowing_variables
# Too many false positives for these
#  - undefined_methods
#  - undefined_variables
#  - unused_variables
  - useless_equality_checks
react-webpack-rails-tutorial $ ruby-lint .
react-webpack-rails-tutorial $ 
```

I can't reproduce it using 2.1 either:

```
react-webpack-rails-tutorial $ chruby 2.1
greact-webpack-rails-tutorial $ gem install ruby-lint
ruby-lint .
Fetching: ruby-lint-2.0.3.gem (100%)
Please report any issues at: https://github.com/YorickPeterse/ruby-lint/issues/new
Successfully installed ruby-lint-2.0.3
1 gem installed
react-webpack-rails-tutorial $ ruby-lint .
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.5-compliant syntax, but you are running 2.1.4.
react-webpack-rails-tutorial $ ruby-lint --version
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.5-compliant syntax, but you are running 2.1.4.
ruby-lint v2.0.3 on ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-linux]
```

**Comment by YorickPeterse** [comment] 2015-06-15 20:53
Closing this due to lack of feedback and me being unable to reproduce this problem. Feel free to re-open if the problem persists and there's a reliable way of reproducing it.

**Closed by YorickPeterse** 2015-06-15 20:53 UTC
